In [9]:
%run ../src/ingestion.py

Processing: Zerdab...
Processing: Quba...
Processing: Lenkeran...
Processing: Baki...
Processing: Saatli...

✅ Data successfully collected using config settings.
Start Date: 2026-04-13
End Date: 2026-04-22
Cities processed: ['Zerdab', 'Quba', 'Lenkeran', 'Baki', 'Saatli']

In [10]:
%run ../notebooks/day_02_ingestion.ipynb

✅ Config imported successfully!
Start Date: 2026-04-13
Inference Data Ingestion started: 2026-04-13 to 2026-04-22
Processing: Zerdab...
Processing: Quba...
Processing: Lenkeran...
Processing: Baki...
Processing: Saatli...
✅ Zerdab: 17 rows (10d History + 7d Forecast) saved to zerdab_inference.parquet
✅ Quba: 17 rows (10d History + 7d Forecast) saved to quba_inference.parquet
✅ Lenkeran: 17 rows (10d History + 7d Forecast) saved to lenkeran_inference.parquet
✅ Baki: 17 rows (10d History + 7d Forecast) saved to baki_inference.parquet
✅ Saatli: 17 rows (10d History + 7d Forecast) saved to saatli_inference.parquet

🚀 All data for prediction is ready!

In [11]:
%run ../src/database.py

In [4]:
%run ../notebooks/day_03_database.ipynb
#olmasada olar

✅ Schemas created, tables defined, and raw data loaded successfully!
--- 1. Row Counts per City ---

       city  total_rows
0      Baki          17
1    Saatli          17
2    Zerdab          17
3  Lenkeran          17
4      Quba          17

--- 2. Date Range Verification ---

       city start_date   end_date
0      Baki 2026-04-13 2026-04-29
1  Lenkeran 2026-04-13 2026-04-29
2      Quba 2026-04-13 2026-04-29
3    Zerdab 2026-04-13 2026-04-29
4    Saatli 2026-04-13 2026-04-29

--- 3. Duplicate Checks ---
✅ PASS: No duplicate date-city combinations found.

--- 4. Data Type Verification ---

                       column_name column_type
0                             city     VARCHAR
1                             date   TIMESTAMP
2              temperature_2m_mean      DOUBLE
3   et0_fao_evapotranspiration_sum      DOUBLE
4                sunshine_duration      DOUBLE
5          shortwave_radiation_sum      DOUBLE
6        relative_humidity_2m_mean      DOUBLE
7            surface_pressure_mean      DOUBLE
8                precipitation_sum      DOUBLE
9              precipitation_hours      DOUBLE
10              wind_speed_10m_max      DOUBLE
11                cloud_cover_mean      DOUBLE
12             wind_gusts_10m_mean      DOUBLE
13     soil_moisture_0_to_7cm_mean      DOUBLE
14                       data_type     VARCHAR

--- Average Temperature per City per Year ---

       city  year  avg_temp
0      Baki  2026     12.65
1  Lenkeran  2026     13.68
2      Quba  2026      7.72
3    Saatli  2026     14.14
4    Zerdab  2026     14.44

--- Highest Variance in Daily Precipitation ---

     city  precip_variance
0  Saatli          17.4513

--- Top 10 Hottest Days ---

       city exact_date  temperature_2m_mean
0    Zerdab 2026-04-27            17.935665
1    Saatli 2026-04-27            17.285166
2    Zerdab 2026-04-23            16.585667
3    Zerdab 2026-04-19            16.541666
4    Saatli 2026-04-19            16.497917
5    Zerdab 2026-04-24            16.071085
6  Lenkeran 2026-04-27            15.973916
7    Zerdab 2026-04-25            15.783584
8  Lenkeran 2026-04-20            15.713666
9    Zerdab 2026-04-20            15.597917

--- Days with Zero Precipitation per City per Year ---

       city  year  zero_precip_days
0      Baki  2026              11.0
1    Saatli  2026              10.0
2  Lenkeran  2026               9.0
3    Zerdab  2026               9.0
4      Quba  2026               6.0

,city,date,temperature_2m_mean,et0_fao_evapotranspiration_sum,sunshine_duration,shortwave_radiation_sum,relative_humidity_2m_mean,surface_pressure_mean,precipitation_sum,precipitation_hours,wind_speed_10m_max,cloud_cover_mean,wind_gusts_10m_mean,soil_moisture_0_to_7cm_mean,data_type
0,Baki,2026-04-13,10.950000,2.437522,32400.000000,18.049999,82.486885,1015.722656,6.7,5.0,30.360830,75.750000,44.744991,0.260292,historical
1,Baki,2026-04-14,11.312499,2.305472,33141.066406,15.010000,79.314529,1021.701904,2.4,13.0,15.856354,79.000000,22.964998,0.283333,historical
2,Baki,2026-04-15,11.702085,3.136395,41735.414062,20.240000,69.572823,1024.161987,0.3,3.0,15.484185,47.250000,28.199997,0.277208,historical
3,Baki,2026-04-16,13.097917,3.106966,42755.191406,19.440001,65.637993,1023.956787,0.0,0.0,12.362475,20.416666,14.085001,0.260625,historical
4,Baki,2026-04-17,12.995834,3.021810,42742.210938,21.790001,80.436111,1024.379028,0.0,0.0,16.036171,22.750000,25.874998,0.239250,historical
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
80,Zerdab,2026-04-25,15.783584,5.059198,45101.753906,21.639999,49.250000,1014.504822,0.0,0.0,38.349712,28.250000,44.775002,NaN,forecast
81,Zerdab,2026-04-26,14.550251,3.478364,39786.136719,20.170000,66.541664,1020.430420,0.0,0.0,20.469410,83.375000,16.829998,NaN,forecast
82,Zerdab,2026-04-27,17.935665,4.894565,35427.316406,20.969999,61.875000,1010.461914,0.3,3.0,34.114628,87.416664,28.814999,NaN,forecast
83,Zerdab,2026-04-28,15.439916,3.300727,19404.607422,11.810000,55.916668,1019.141907,0.0,0.0,31.869658,91.166664,29.291250,NaN,forecast
84,Zerdab,2026-04-29,13.991418,3.991863,46938.007812,22.670000,58.333332,1021.894714,0.0,0.0,15.815435,40.541668,18.599998,NaN,forecast

In [12]:
"""import duckdb

# database.py-də təyin etdiyin yola uyğun qoşuluruq
conn = duckdb.connect('../data/weather_pipeline.duckdb')"""

In [4]:
# 1. Create connection
conn = get_connection()

# 2. Set up the database (schemas and tables) from scratch
create_schemas(conn)
create_raw_tables(conn)

# 3. Now load data from parquet files
load_raw_data(conn)

print("Database is ready and data has been loaded!")

Database is ready and data has been loaded!

In [13]:
%run ../src/cleaning.py

In [14]:
%run ../src/features.py
created_features_df=create_features(conn)

🔧 Generating features from staging.weather_daily ...
✅ Features computed: day_of_year, precip_sum_7d, prev_soil_moisture

Data now has 85 rows and 18 columns.

📊 Example of engineered data:
city       date  temperature_2m_mean  et0_fao_evapotranspiration_sum  sunshine_duration  shortwave_radiation_sum  relative_humidity_2m_mean  surface_pressure_mean  precipitation_sum  precipitation_hours  wind_speed_10m_max  cloud_cover_mean  wind_gusts_10m_mean  soil_moisture_0_to_7cm_mean  data_type  day_of_year  precip_sum_7d  prev_soil_moisture
Baki 2026-04-13            10.950000                        2.437522       32400.000000                18.049999                  82.486885            1015.722656                6.7                  5.0           30.360830         75.750000            44.744991                     0.260292 historical          103            6.7                 NaN
Baki 2026-04-14            11.312499                        2.305472       33141.066406                15.010000                  79.314529            1021.701904                2.4                 13.0           15.856354         79.000000            22.964998                     0.283333 historical          104            9.1            0.260292
Baki 2026-04-15            11.702085                        3.136395       41735.414062                20.240000                  69.572823            1024.161987                0.3                  3.0           15.484185         47.250000            28.199997                     0.277208 historical          105            9.4            0.283333
Baki 2026-04-16            13.097917                        3.106966       42755.191406                19.440001                  65.637993            1023.956787                0.0                  0.0           12.362475         20.416666            14.085001                     0.260625 historical          106            9.4            0.277208
Baki 2026-04-17            12.995834                        3.021810       42742.210938                21.790001                  80.436111            1024.379028                0.0                  0.0           16.036171         22.750000            25.874998                     0.239250 historical          107            9.4            0.260625
Baki 2026-04-18            13.668750                        2.861732       43815.843750                22.580000                  83.649406            1016.915588                0.0                  0.0           22.350464         27.541666            38.280003                     0.212958 historical          108            9.4            0.239250
Baki 2026-04-19            15.177083                        3.267373       41231.125000                21.450001                  80.289223            1006.191345                0.1                  1.0           20.803045         51.625000            34.079998                     0.188708 historical          109            9.5            0.212958
Baki 2026-04-20            13.847917                        2.064010        8520.239258                 9.200000                  76.577911            1011.642517                1.8                  6.0           24.725605         95.208336            47.235001                     0.188417 historical          110            4.6            0.188708
Baki 2026-04-21            10.787499                        1.553613       13218.458984                 9.220000                  83.323708            1015.477234                6.4                 11.0           22.158285         75.750000            38.565002                     0.244083 historical          111            8.6            0.188417
Baki 2026-04-22            13.112499                        3.127617       43021.062500                20.930000                  80.909668            1013.233398                0.0                  0.0           18.501513         51.833332            25.094997                     0.240625 historical          112            8.3            0.244083

✅ Features written to analytics.weather_features.

In [8]:
created_features_df

,city,date,temperature_2m_mean,et0_fao_evapotranspiration_sum,sunshine_duration,shortwave_radiation_sum,relative_humidity_2m_mean,surface_pressure_mean,precipitation_sum,precipitation_hours,wind_speed_10m_max,cloud_cover_mean,wind_gusts_10m_mean,soil_moisture_0_to_7cm_mean,data_type,day_of_year,precip_sum_7d,prev_soil_moisture
0,Baki,2026-04-13,10.950000,2.437522,32400.000000,18.049999,82.486885,1015.722656,6.7,5.0,30.360830,75.750000,44.744991,0.260292,historical,103,6.7,NaN
1,Baki,2026-04-14,11.312499,2.305472,33141.066406,15.010000,79.314529,1021.701904,2.4,13.0,15.856354,79.000000,22.964998,0.283333,historical,104,9.1,0.260292
2,Baki,2026-04-15,11.702085,3.136395,41735.414062,20.240000,69.572823,1024.161987,0.3,3.0,15.484185,47.250000,28.199997,0.277208,historical,105,9.4,0.283333
3,Baki,2026-04-16,13.097917,3.106966,42755.191406,19.440001,65.637993,1023.956787,0.0,0.0,12.362475,20.416666,14.085001,0.260625,historical,106,9.4,0.277208
4,Baki,2026-04-17,12.995834,3.021810,42742.210938,21.790001,80.436111,1024.379028,0.0,0.0,16.036171,22.750000,25.874998,0.239250,historical,107,9.4,0.260625
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
80,Zerdab,2026-04-25,15.783584,5.059198,45101.753906,21.639999,49.250000,1014.504822,0.0,0.0,38.349712,28.250000,44.775002,NaN,forecast,115,15.3,NaN
81,Zerdab,2026-04-26,14.550251,3.478364,39786.136719,20.170000,66.541664,1020.430420,0.0,0.0,20.469410,83.375000,16.829998,NaN,forecast,116,15.3,NaN
82,Zerdab,2026-04-27,17.935665,4.894565,35427.316406,20.969999,61.875000,1010.461914,0.3,3.0,34.114628,87.416664,28.814999,NaN,forecast,117,12.2,NaN
83,Zerdab,2026-04-28,15.439916,3.300727,19404.607422,11.810000,55.916668,1019.141907,0.0,0.0,31.869658,91.166664,29.291250,NaN,forecast,118,0.7,NaN
84,Zerdab,2026-04-29,13.991418,3.991863,46938.007812,22.670000,58.333332,1021.894714,0.0,0.0,15.815435,40.541668,18.599998,NaN,forecast,119,0.7,NaN

In [19]:
import duckdb

# database.py-də təyin etdiyin yola uyğun qoşuluruq
conn = duckdb.connect('../data/weather_pipeline.duckdb')

In [26]:
city_stats = conn.execute("""
    SELECT city, COUNT(*) as row_count, MIN(date) as start_date, MAX(date) as end_date 
    FROM raw.weather_daily 
    GROUP BY city
""").df()
display(city_stats)

       city  row_count start_date   end_date
0      Baki         17 2026-04-13 2026-04-29
1  Lenkeran         17 2026-04-13 2026-04-29
2      Quba         17 2026-04-13 2026-04-29
3    Zerdab         17 2026-04-13 2026-04-29
4    Saatli         17 2026-04-13 2026-04-29

In [1]:
conn.close()

NameError: name 'conn' is not defined